dist: xenial
language: python
python:
  - "3.7"
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
script: 
  - pytest --cov=hermes --cov-report term-missing
after_script:
  - codecov