version: "3"
services:
  cache_map:
    container_name: cache_map
    image: redis
    ports:
      - "6379:6379"
        
  hermes:
    container_name: hermes
    image: hermes
    build:
      context: .
    environment:
      - REDIS_HOST=cache_map
      - USE_CORS=true
    ports:
      - "4878:4878"

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/:/specs/
    environment:
      - BASE_URL=/apidocs/
      - SWAGGER_JSON=/specs/openapi.yml
    ports:
      - "4888:8080"