openapi: 3.0.2
info:
  title: Hermes
  description: Pipelining for NCATS Reasoner services
  contact:
    email: patrick@covar.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: http://localhost:4878/
paths:
  /job/{job_id}:
    get:
      parameters:
      - in: path
        name: job_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Job info
  /result/{job_id}:
    get:
      parameters:
      - in: path
        name: job_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Message resulting from job
  /run:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                actions:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      options:
                        type: object
              additionalProperties: false
              required:
              - message
              - actions
              example:
                message:
                  query_graph:
                    nodes:
                    - id: n00
                      curie: MONDO:0005737
                    - id: n01
                      type: gene
                    edges:
                    - id: e00
                      source_id: n00
                      target_id: n01
                actions:
                - url: http://robokop.renci.org:4868/answer
                  options: {}
      responses:
        '200':
          description: Message of the same format as the input.
